language: cpp
before_install:
  - $CXX --version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo apt-get install libeigen3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
  - sudo apt-get update -qq
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov
script:
  - mkdir build
  - cd build
  - cmake -DBuildTest=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - mkdir out
  - lcov --capture --initial --no-external --directory . --base-directory .. --output-file out/initial.info
  - ./unit_tests
after_success:
  - cd build
  - lcov --capture --no-external --directory . --base-directory .. --output-file out/final.info
  - lcov --add-tracefile out/initial.info --add-tracefile out/final.info --output-file out/coverage.info
  - coveralls-lcov --repo-token XQlVreS1r1o5V7qn14UiqF3W3kZiy7TUM out/coverage.info