language: cpp
before_install:
  - $CXX --version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev
  - dpkg -S /usr/include/boost/version.hpp
  - sudo add-apt-repository ppa:fenics-packages/fenics -y
  - sudo apt-get update -y
  - sudo apt-get -y install fenics
  - sudo apt-get -y dist-upgrade
install:
  - sudo pip install cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake -DBuildTest=ON ..
  - make
  - ./unit_tests
after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --gcov-options '\-lp' --gcov 'gcov-4.9'