language: cpp
before_install:
  - $CXX --version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  # Set this to the name of your Boost library
  # Autodetect library name by using the following code: - PROJECT_TO_TEST=$(basename $(pwd))
  - PROJECT_TO_TEST=$(basename $(pwd))

  # Autodetect Boost branch by using the following code: - BRANCH_TO_TEST=`git rev-parse --abbrev-ref HEAD`
  # or by - BRANCH_TO_TEST=$TRAVIS_BRANCH or just directly specify it
  - BRANCH_TO_TEST=$TRAVIS_BRANCH

  # From this point and below code is same for all the Boost libs
  # Cloning Boost libraries (fast nondeep cloning)
  - PROJECT_DIR=`pwd`
  - BOOST=$HOME/boost-local
  - git init $BOOST
  - cd $BOOST
  - git remote add --no-tags -t $BRANCH_TO_TEST origin https://github.com/boostorg/boost.git
  - git fetch --depth=1
  - git checkout $BRANCH_TO_TEST
  - git submodule update --init --merge
  - git remote set-branches --add origin $BRANCH_TO_TEST
  - git pull --recurse-submodules
  - git submodule update --init
  - git checkout $BRANCH_TO_TEST
  - git submodule foreach "git reset --quiet --hard; git clean -fxd"
  - git reset --hard; git clean -fxd
  - git status
  - rm -rf $BOOST/libs/$PROJECT_TO_TEST
  - mv $PROJECT_DIR/../$PROJECT_TO_TEST/ $BOOST/libs/$PROJECT_TO_TEST
  - PROJECT_DIR=$BOOST/libs/$PROJECT_TO_TEST
  - ./bootstrap.sh
  - ./b2 headers
install:
  - sudo pip install cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake .. -DBuildTest=ON
  - make
  - ./unit_tests
after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --gcov-options '\-lp' --gcov 'gcov-4.9'